### ISSUE TITLE
function profile_field_dynamicmenu should probably not throw debugging notice?

### ISSUE THREAD

**Issue by danmarsden** [tunele/moodle-profilefield_dynamicmenu#2]
https://github.com/tunele/moodle-profilefield_dynamicmenu/blob/master/dynamicmenu/field.class.php#L77

the debugging notice should only really be thrown when this plugin is installed in versions 3.1 and higher. I assume you have developed this for versions lower than 3.1 as well? - I'd be interested to know if you actually need this function at all? - you shouldn't need it for Moodle 3.1 sites but it's possible that the function might be needed in older versions (I haven't actually checked) but when it's installed in older versions it probably shouldn't throw the debugging notice.

**Comment by tunele** [comment]
Yep you are right... I think removing the debugging notice should be the best solution

**Comment by danmarsden** [comment]
cool.
