### ISSUE TITLE
not clear that 2 values are required by the query

### ISSUE THREAD

**Issue by danmarsden** [tunele/moodle-profilefield_dynamicmenu#4]
the documentation/description on the plugins db entry should be improved to state that the sql query used must return an "id" field along with the actual text value used - I assume this means that the value stored in the database will be the "id" field and every time it is display it is translated? - I think that makes sense but it should be clear in the docs & description of the plugin.

**Comment by tunele** [comment]
Modified both readme and plugin description here:
https://moodle.org/plugins/profilefield_dynamicmenu
it should be clear now

**Comment by danmarsden** [comment]
looks better - just a few typos in the text in the description that you might want to tidy up 
"moolde" - "mu " " st"  :-)

**Comment by tunele** [comment]
tidied up. please let me know if there are any other mistakes/typos etc :-)
