### ISSUE TITLE
option values/text should be encoded

### ISSUE THREAD

**Issue by danmarsden** [tunele/moodle-profilefield_dynamicmenu#5]
results returned from the sql query could potentially contain html/double quotes etc. it looks like the text is wrapped in format_string which is good but the $key is used in raw form as returned from the query. If the key is supposed to be an integer then the code should force this and prevent other values from being used... I managed to break the page by getting the query to return html/crap in the $key value.

**Comment by tunele** [comment]
this should fix the problem. It not, please let me know the query you write to reproduce it

**Comment by danmarsden** [comment]
looks like you've covered it well.
